# Foundations for efficiencies

¿Qué es código eficiente?

- Se ejecuta rápido y tiene poca latencia entre la ejecución y la devolución del resultado
- Consume los recursos eficientemente

¿Qué es Pythonic?

- Se enfoca en la legibilidad
- Sigue las buenas prácticas y principios de Python.

Aunque python soporte código que no sigue esas prácticas, tiende a correr más lento.

In [1]:
numbers = [1,2,3]

# Non pythonic
doubled_numbers = []

for i in range(len(numbers)):
    doubled_numbers.append(numbers[i] * 2)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 6.91 µs


In [2]:
#Pythonic
doubled_numbers = [x * 2 for x in numbers]

CPU times: user 7 µs, sys: 1 µs, total: 8 µs
Wall time: 10 µs


In [3]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## A taste of things to come

Suppose you wanted to collect the names in the above list that have six letters or more. In other programming languages, the typical approach is to create an index variable (i), use i to iterate over the list, and use an if statement to collect the names with six letters or more:

In [4]:
# Print the list created using the Non-Pythonic approach
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


A more Pythonic approach would loop over the contents of names, rather than using an index variable

In [6]:
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


The best Pythonic way of doing this is by using list comprehension.

In [8]:
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


## Building with built-ins

Python standart library: parte de cualquier instalación de Python.

- Built in types: list, tuples, set, dict, etc.
- Built in functions: print, len, range, round, enumerate, map, zip, etc.
- Built in modules: os, sys, itertools, collections, math, etc.

range(): para crear una secuencia de números. Le damos un inicio y un fin (exclusivo).
Devuelve un objeto range, para tenerlos en una lista hay que convertirlo.

In [12]:
nums = range(0,10)
nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Si no le ponés inicio arranca en 0.

In [13]:
nums = range(10)
nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


También acepta un parámetro de step

In [15]:
even_numbers = range(2, 11, 2)
print(list(even_numbers))

[2, 4, 6, 8, 10]


enumerate(): crea un par índice valor para cada item en el objeto que le pases.
Devuelve un objeto así que hay que pasarlo a lista.

In [16]:
letters = ['a', 'b', 'c']
indexed_letters = enumerate(letters)
print(list(indexed_letters))

[(0, 'a'), (1, 'b'), (2, 'c')]


También se le puede decir un start

In [17]:
letters = ['a', 'b', 'c']
indexed_letters = enumerate(letters,start=3)
print(list(indexed_letters))

[(3, 'a'), (4, 'b'), (5, 'c')]


map(): aplica una función a todos los elementos del objeto que le pases. Se le pasa la función y el objeto. Devuelve un objeto y lo convierto a lista.

In [19]:
nums = [1.3,4.5]
list(map(round, nums))

[1, 4]

Map con lambda:

In [20]:
nums = [1,2,3]
list(map(lambda x: x**2, nums))

[1, 4, 9]

## Built-in practice: range()

In [21]:
# Create a range object that goes from 0 to 5
nums = range(6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
print(nums_list2)

[1, 3, 5, 7, 9, 11]

## Built-in practice: enumerate()

In [22]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i, name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names,start=1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


## Built-in practice: map()

In [23]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


## The power of NumPy arrays

Alternativa más rápida y eficiente a las listas de Python. Para crear uno:

In [24]:
import numpy as np
np_array = np.array(range(5))
np_array

array([0, 1, 2, 3, 4])

 - Son homogéneos: todos los elementos son del mismo tipo. Esto hace que no se tenga que chequear el tipo entonces sea más rápido. Para ver el tipo:

In [25]:
np_array.dtype

dtype('int64')

In [27]:
np_array_floats = np.array([1, 2.5])
np_array_floats

array([1. , 2.5])

El integer se convirtió a float.

- También soportan broadcasting: puedo aplicarle una operación a un array entero, que en listas de Python no se puede:


In [29]:
[1,2,3] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Podríamos hacerlo en un for o con list comprehension, pero no son las formas más eficientes de hacerlo.
Numpy arrays vectorizan las operaciones entonces las aplica a todo el array a la vez.

In [30]:
np_array ** 2

array([ 0,  1,  4,  9, 16])

Otra ventaja son los índices. En un arreglo de 1 dimensión es igual que una lista:


In [33]:
print(np_array[1])
print(np_array[1:3])
print([1,2,3][1])
print([1,2,3][1:3])

1
[1 2]
2
[2, 3]


Pero cuando hay más dimensiones es más fácil de escribir:

In [38]:
#List
nums_2 = [[1,2,3], [4,5,6]]
print(nums_2[0][1])
#Primer elemento de cada fila
print([row[0] for row in nums_2])

#Array
array_2 = np.array(nums_2)
print(array_2[0,1])
#Primer elemento de cada fila
print(array_2[:,0])

2
[1, 4]
2
[1 4]


También tiene boolean indexing.

In [40]:
numbers = np.array([1,2-4,-5,6])
numbers[numbers > 0]

array([1, 6])

Para hacerlo con una lista necesitarías un for o una list comprehension

In [41]:
numbers_list = [1,2-4,-5,6]
[n for n in numbers_list if n > 0]

[1, 6]

## Practice with NumPy arrays

In [43]:
nums = np.array([[ 1, 2,3,  4,  5],
 [ 6,  7,  8,  9, 10]])

# Print second row of nums
print(nums[1])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

## Bringing it all together: Festivus!

In [ ]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')